server:
  port: 10000
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: submission

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    username: root
    password: 123
    url: jdbc:mysql://127.0.0.1:3306/onlinejudge?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  #mybatis-plus配置
mybatis-plus:
  configuration:
    #日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deFlag
      logic-delete-value: 0
      logic-not-delete-value: 1
      id-type: auto
