server:
  port: 10000
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: submission
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://127.0.0.1:3306/onlinejudge?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


